spring:
  datasource: # データベース接続に関する設定
    url: jdbc:postgresql://localhost:15432/todo_db
    username: postgres
    password: postgres
mybatis: # MyBatisフレームワークに関する設定
  # MyBatis の マッパーXMLファイルが格納されている場所を指定します。
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: wakusan61.spring.todo.model
logging:
  level:
    org.mybatis: DEBUG
