spring:
  datasource: # データベース接続に関する設定
    url: jdbc:postgresql://localhost:15432/todo_db
    username: postgres
    password: postgres
mybatis: # MyBatisフレームワークに関する設定
  configuration:
    useGeneratedKeys: true # MyBatis が自動生成キーを使用できるようにする
  mapper-locations: classpath:mapper/*.xml   # MyBatis の マッパーXMLファイルが格納されている場所を指定します。
  type-aliases-package: wakusan61.spring.todo.model # MyBatis のエイリアスを指定します。
logging:
  level:
    org.mybatis: DEBUG
