version: '3.8'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: